title: Just some stuff
author: Maskime
email: hello@maxoumask.com
description: > # this means to ignore newlines until "baseurl:"
  Trying stuff, living the life of a true Millenial developer that uses Github to publish everything

# social links
twitter_username: MaxouMask
github_username:  Maskime

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
